In [3]:
# import pandas as pd


# csv_file1 = 'tmdb_5000_movies.csv'
# csv_file2 = 'movies.csv'

# df1 = pd.read_csv(csv_file1)
# df2 = pd.read_csv(csv_file2)

# df2.rename(columns={'name': 'title'}, inplace=True)
# df = pd.merge(df1, df2, on='title')
# df.drop(['budget_x','keywords','genres','homepage','id','original_title','rating','gross',\
#          'budget_y','spoken_languages','runtime_y','production_companies','revenue',\
#          'production_countries','tagline','released','votes','year','status','score',\
#          'popularity'], axis=1, inplace=True)
# df.rename(columns={'original_language': 'language','runtime_x': 'runtime'}, inplace=True)
# # df.rename(columns={'original_language': 'language','runtime_x': 'runtime'}, inplace=True)

# #df.set_index('title', inplace=True)
# df.dropna(inplace=True)
# df

,language,overview,release_date,runtime,title,vote_average,vote_count,company,country,director,genre,star,writer
0,en,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,162.0,Avatar,7.2,11800,Twentieth Century Fox Film Corporation,UK,James Cameron,Action,Sam Worthington,James Cameron
1,en,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,169.0,Pirates of the Caribbean: At World's End,6.9,4500,Walt Disney Pictures,USA,Gore Verbinski,Action,Johnny Depp,Ted Elliott
2,en,A cryptic message from Bond’s past sends him o...,2015-10-26,148.0,Spectre,6.3,4466,B24,UK,Sam Mendes,Action,Daniel Craig,John Logan
3,en,Following the death of District Attorney Harve...,2012-07-16,165.0,The Dark Knight Rises,7.6,9106,Warner Bros.,UK,Christopher Nolan,Action,Christian Bale,Jonathan Nolan
4,en,"John Carter is a war-weary, former military ca...",2012-03-07,132.0,John Carter,6.1,2124,Walt Disney Pictures,USA,Andrew Stanton,Action,Taylor Kitsch,Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,en,Two business executives--one an avowed misogyn...,1997-01-19,97.0,In the Company of Men,6.8,44,Alliance Atlantis Communications,Canada,Neil LaBute,Comedy,Aaron Eckhart,Neil LaBute
3163,en,The boredom of small town life is eating Bill ...,2009-08-14,85.0,Rampage,6.0,131,De Laurentiis Entertainment Group (DEG),USA,William Friedkin,Drama,Michael Biehn,William P. Wood
3164,en,"Presents a day in the life in Austin, Texas am...",1990-07-27,97.0,Slacker,6.4,77,Detour Filmproduction,USA,Richard Linklater,Comedy,Richard Linklater,Richard Linklater
3165,en,Friends/fledgling entrepreneurs invent a devic...,2004-10-08,77.0,Primer,6.9,658,ERBP,USA,Shane Carruth,Drama,Shane Carruth,Shane Carruth
3166,es,El Mariachi just wants to play his guitar and ...,1992-09-04,81.0,El Mariachi,6.6,238,Columbia Pictures Corporation,USA,Robert Rodriguez,Action,Carlos Gallardo,Robert Rodriguez

In [21]:
import pandas as pd
import matplotlib.pyplot as plt

csv_file1 = 'tmdb_5000_movies.csv'
csv_file2 = 'movies.csv'

df1 = pd.read_csv(csv_file1)
df2 = pd.read_csv(csv_file2)

df2.rename(columns={'name': 'title'}, inplace=True)
df = pd.merge(df1, df2, on='title')
df.drop(['budget_x','keywords','genres','homepage','original_title','rating','gross',\
         'budget_y','spoken_languages','runtime_y','production_companies','revenue',\
         'production_countries','tagline','released','votes','year','status','score',\
         'popularity'], axis=1, inplace=True)
df.rename(columns={'original_language': 'language','runtime_x': 'runtime'}, inplace=True)

#df.set_index('title', inplace=True)
df.dropna(inplace=True)


    # 2006 - 2016
df['release_date'] = df['release_date'].str.replace('-', '')
df['release_date'] = df['release_date'].map(lambda x: int(x)//10000)
movie_of_year = df.groupby('release_date', group_keys=False).apply(lambda x: x.sort_values('vote_average',ascending=False))\
        .groupby('release_date').first().reset_index()
movie_of_year.drop(['overview', 'writer', 'star', 'runtime', 'company',
                        'genre', 'vote_count'], axis=1, inplace=True)
movie_of_year = movie_of_year[movie_of_year.release_date>2005].reset_index()
movie_of_year.drop(['index'], axis=1, inplace=True)
movie_of_year.to_csv('movie_of_year.csv',index=False)

In [37]:

df4 = pd.read_csv('movie_of_year.csv')
df4.set_index('release_date', inplace=True)
# if year not in df4.index:
#     ptint(1)
# else:
#     print(2)
#df4.dtypes
    #
movie=df4.loc[2006]
movie

id                           1124
language                       en
title                The Prestige
vote_average                    8
country                       USA
director        Christopher Nolan
Name: 2006, dtype: object